import { load } from 'cheerio';

const SKIP_TAGS = new Set(['script', 'style']);

// Blog post HTML from the editor is heavy with inline-styled marketing
// blocks (see the "Custom Designs" / "Templates" menus in the TinyMCE
// config) — the tags/attributes/CSS never need translating, only the
// human-readable text between them. Pulling just that text out keeps the
// translation prompt and response small (and model-agnostic — the saving
// applies the same whether we call Haiku, Sonnet, or anything else),
// instead of round-tripping the entire HTML skeleton through the model
// once per target language.

// Extracts translatable text nodes from an HTML fragment, in document order.
// Returns the cheerio instance (so the same tree can be mutated afterward)
// and the list of text-node references alongside their current text.
export function extractTextSegments(html) {
  const $ = load(html || '', null, false);
  const textNodes = [];

  const walk = (el) => {
    const children = $(el).contents().toArray();
    for (const child of children) {
      if (child.type === 'text') {
        if (child.data && child.data.trim()) {
          textNodes.push(child);
        }
      } else if (child.type === 'tag' && !SKIP_TAGS.has(child.name)) {
        walk(child);
      }
    }
  };
  walk($.root().get(0));

  return { $, textNodes, segments: textNodes.map((n) => n.data) };
}

// Writes translated strings back into the same node positions captured by
// extractTextSegments, then serializes the (unchanged) HTML structure back
// out — so tags/attributes/styles are guaranteed identical to the source,
// never regenerated by the model.
export function injectTextSegments($, textNodes, translatedSegments) {
  textNodes.forEach((node, i) => {
    const replacement = translatedSegments?.[i];
    if (typeof replacement === 'string' && replacement.length > 0) {
      node.data = replacement;
    }
  });
  return $.root().html() || '';
}
